name = "Dracula"

[colors]
background = "#282A36"
foreground = "#F8F8F2"
selected = "#44475A"
directory = "#BD93F9"
executable = "#50FA7B"
hidden = "#6272A4"
symlink = "#8BE9FD"
parent_dir = "#FF79C6"
status_bar_bg = "#21222C"
status_bar_fg = "#F8F8F2"
status_bar_active = "#BD93F9"
ui_secondary = "#6272A4"
ui_border = "#44475A"
ui_error = "#FF5555"
ui_warning = "#FFB86C"
ui_accent = "#FF79C6"
ui_info = "#8BE9FD"
ui_success = "#50FA7B"
