name = "Nord"

[colors]
background = "#2E3440"
foreground = "#D8DEE9"
selected = "#434C5E"
directory = "#88C0D0"
executable = "#A3BE8C"
hidden = "#4C566A"
symlink = "#81A1C1"
parent_dir = "#B48EAD"
status_bar_bg = "#3B4252"
status_bar_fg = "#ECEFF4"
status_bar_active = "#88C0D0"
ui_secondary = "#4C566A"
ui_border = "#434C5E"
ui_error = "#BF616A"
ui_warning = "#EBCB8B"
ui_accent = "#B48EAD"
ui_info = "#81A1C1"
ui_success = "#A3BE8C"
