name = "Gruvbox Dark"

[colors]
background = "#282828"
foreground = "#EBDBB2"
selected = "#3C3836"
directory = "#83A598"
executable = "#B8BB26"
hidden = "#665C54"
symlink = "#8EC07C"
parent_dir = "#D3869B"
status_bar_bg = "#1D2021"
status_bar_fg = "#EBDBB2"
status_bar_active = "#FABD2F"
ui_secondary = "#928374"
ui_border = "#504945"
ui_error = "#FB4934"
ui_warning = "#FE8019"
ui_accent = "#D3869B"
ui_info = "#83A598"
ui_success = "#B8BB26"
