name = "Tokyo Night"

[colors]
# #1A1B26
background = "#1A1B26"
foreground = "#C0CAF5"
selected = "#283457"
directory = "#7AA2F7"
executable = "#9ECE6A"
hidden = "#565F89"
symlink = "#2AC3DE"
parent_dir = "#BB9AF7"
status_bar_bg = "#16161E"
status_bar_fg = "#C0CAF5"
status_bar_active = "#7AA2F7"
ui_secondary = "#565F89"
ui_border = "#292E42"
ui_error = "#F7768E"
ui_warning = "#E0AF68"
ui_accent = "#BB9AF7"
ui_info = "#7AA2F7"
ui_success = "#9ECE6A"
